version: '3.7'
services: 
    uploads3-php:
        build: 
            context: ./..
            dockerfile: docker/php/Dockerfile
        restart: always
        networks: 
            - upload-to-s3-net
        volumes: 
            - ../app:/app

    uploads3-web:
        build:
            context: ./..
            dockerfile: docker/nginx/Dockerfile
        restart: always
        ports:
            - '7071:7071'
        networks: 
            - upload-to-s3-net
        volumes: 
            - ../app:/app
networks: 
    upload-to-s3-net:
